### PR TITLE
metamorphic: fix range key ingestion

### LINKED ISSUE #3062: github.com/cockroachdb/pebble/internal/metamorphic: TestMeta failed
github.com/cockroachdb/pebble/internal/metamorphic.TestMeta [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/12621820?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/12621820?buildTab=artifacts#meta) on refs/heads/master @ [b224e8b90a87](https://github.com/cockroachdb/pebble/commits/b224e8b90a87):

```
=== RUN   TestMeta/execution/random-020
=== PAUSE TestMeta/execution/random-020
=== CONT  TestMeta/execution/random-020
=== RUN   TestMeta/execution/random-026
=== PAUSE TestMeta/execution/random-026
=== CONT  TestMeta/execution/random-026
=== RUN   TestMeta/compare/standard-006
=== RUN   TestMeta/compare/standard-009
=== RUN   TestMeta/execution/random-002
=== PAUSE TestMeta/execution/random-002
=== CONT  TestMeta/execution/random-002
=== RUN   TestMeta/execution/random-004
=== PAUSE TestMeta/execution/random-004
=== CONT  TestMeta/execution/random-004
=== RUN   TestMeta/execution/random-006
=== PAUSE TestMeta/execution/random-006
=== CONT  TestMeta/execution/random-006
=== RUN   TestMeta/execution/random-021
=== PAUSE TestMeta/execution/random-021
=== CONT  TestMeta/execution/random-021
=== RUN   TestMeta/execution/standard-002
=== PAUSE TestMeta/execution/standard-002
=== CONT  TestMeta/execution/standard-002
=== RUN   TestMeta/execution/standard-025
=== PAUSE TestMeta/execution/standard-025
=== CONT  TestMeta/execution/standard-025
=== RUN   TestMeta/execution/standard-026
=== PAUSE TestMeta/execution/standard-026
=== CONT  TestMeta/execution/standard-026
=== RUN   TestMeta/execution/random-005
=== PAUSE TestMeta/execution/random-005
=== CONT  TestMeta/execution/random-005
=== RUN   TestMeta/execution/random-008
=== PAUSE TestMeta/execution/random-008
=== CONT  TestMeta/execution/random-008
=== RUN   TestMeta/execution/standard-008
=== PAUSE TestMeta/execution/standard-008
=== CONT  TestMeta/execution/standard-008
=== RUN   TestMeta/compare/standard-011
=== RUN   TestMeta/execution/random-003
=== PAUSE TestMeta/execution/random-003
=== CONT  TestMeta/execution/random-003
=== RUN   TestMeta/compare/standard-003
=== RUN   TestMeta/compare/standard-010
=== RUN   TestMeta/execution/random-017
=== PAUSE TestMeta/execution/random-017
=== CONT  TestMeta/execution/random-017
=== RUN   TestMeta/execution/standard-003
=== PAUSE TestMeta/execution/standard-003
=== CONT  TestMeta/execution/standard-003
```
<details><summary>Help</summary>
<p>
To reproduce, try:

```bash
go test -tags 'invariants' -exec 'stress -p 1' -timeout 0 -test.v -run TestMeta$ ./internal/metamorphic -seed 1699680580583361137 -ops "uniform:5000-10000"
```
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMeta.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #3063: internal/metamorphic/crossversion/crossversion_test: TestMetaCrossVersion failed
internal/metamorphic/crossversion/crossversion_test.TestMetaCrossVersion [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyPebbleMetamorphicCrossversion/12621822?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlyPebbleMetamorphicCrossversion/12621822?buildTab=artifacts#/) on refs/heads/master @ [b224e8b90a87](https://github.com/cockroachdb/pebble/commits/b224e8b90a87):

```
        iter61.SetBounds("hdmugvzfsd", "hdnlqwgidg")
        iter61.SeekLT("hdnlqwgidg", "")
        iter61.Next("")
        iter61.Next("")
        iter61.Prev("")
        iter61.Next("")
        iter61.Prev("uveyl@43")
        snap43.Get("feqwpzjbep@127")
        iter61.SeekLT("gllg@147", "")
        iter61.First()
        iter63 = snap43.NewIter("nfnopmwhky", "nxwlrrsnqb", 1 /* key types */, 0, 0, false /* use L6 filters */, "" /* masking suffix */)
        db1.RangeKeySet("gicubw", "jpbqdsxecq", "@94", "aykfggsdfgwrynhl")
        iter61.Next("")
        snap43.Get("nrwunep@68")
        iter63.Prev("")
        iter61.NextPrefix()
        iter63.SetBounds("dszce", "etjigkoh")
        iter63.SeekGE("dszce", "")
        iter63.Next("")
        db1.Set("vrlqynizfhd@151", "kfjujxqnqe")
        iter61.Prev("")
        iter61.SeekPrefixGE("feqwpzjbep@21")
        iter63.SeekPrefixGE("gvovvtphcl@62")
        db1.Flush()
        iter61.Next("")
        iter63.First()
        iter61.Last()
        iter63.Last()
        iter61.Close()
        iter63.Close()
        snap43.Close()
        db1.Get("gvovvtphcl@137")
        db1.Set("feqwpzjbep@80", "phpmletwiv")
        db1.Get("hdnls@53")
        db1.Get("feqwpzjbep@60")
        db1.Get("gvovvtphcl@83")
        db1.Get("uveyl@22")
        db1.Get("gvovvtphcl@76")
        db1.Set("gllg@73", "aeqiaypaokxdxwgj")
        db1.Set("agjw@23", "edxybwcgy")
        db1.Get("uveyl@15")
        db1.Set("feqwpzjbep@82", "bdlkdgdl")
        db1.Get("uveyl@150")
        snap45 = db1.NewSnapshot()
        db1.Get("uveyl@75")
        snap45.Close()
        db1.Close()
        
        		
        --- FAIL: TestMetaCrossVersion/execution-master/sha=043c3795-seed=7144057419648618075-opts=random-022(sha=db91e5c9-seed=3808559344755705723-opts=random-001(sha=ffd5ce9c-seed=7809109350420410039-opts=standard-000(sha=4ddacdaf-seed=12929196215159896102-opts=random-014(<empty>)))) (366.41s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMetaCrossVersion.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by jbowens**
Previously, the integration of range keys into the metamorphic test's ingest operation had a couple of bugs:

When constructing the sstable to ingest, the batch's range keys were fragmented, their sequence numbers zeroed and then written to the sstable. This allowed for a range key to be both SET and UNSET at the same suffix at the same sequence number, which is prohibited. Within a sequence number, range keys are required to be internally consistent. This commit resolves this issue by first coalescing the range keys and writing them out to the table. This mirrors the treatment of point keys in which we drop all but the most recent InternalKey at any particular user key.

When the ingestUsingApply test option was set, the batch's range keys were fragmented and then the individual keys were written to the collapsed batch in Trailer descending order through the user-facing mutation methods. This effectively reversed the order of precedence for all range keys, assigning earlier sequence numbers to the range keys that previously had relatively later sequence numbers. This commit adapts the collapseBatch function to treat range keys slightly differently, instead iterating through the batch and copying the keys verbatim to the collapsed batch through the AddInternalKey method. This allows the ingestUsingApply batch to apply the range keys in their unfragmented form, deferring fragmentation.

Fix #3062.
Fix #3063.

### CODE REVIEW

File: metamorphic/ops.go [hunk 1]
```diff
@@ -709,27 +727,28 @@ func (o *ingestOp) collapseBatch(
 		pointIter = nil
 	}
 
+	// There's no equivalent of a MERGE operator for range keys, so there's no
+	// need to collapse the range keys here. Rather than reading the range keys
+	// from `rangeKeyIter`, which will already be fragmented, read the range
+	// keys from the batch and copy them verbatim. This marginally improves our
+	// test coverage over the alternative approach of pre-fragmenting and
+	// pre-coalescing before writing to the batch.
```
Comment (itsbilal) [inline metamorphic/ops.go:735]: nice!

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by jbowens** [comment]
TFTR!
