### PR TITLE
lint: use `go run path@version` syntax for lint binaries

### LINKED ISSUE #1319: internal/lint: test assumes a program exists in $PATH
Was running the tests and ran into this one:

```
--- FAIL: TestLint (0.72s)
    --- FAIL: TestLint/TestGolint (0.00s)
        lint_test.go:30: 
            	Error Trace:	lint_test.go:30
            	           				lint_test.go:67
            	Error:      	Received unexpected error:
            	           	exec: "golint": executable file not found in $PATH
            	Test:       	TestLint/TestGolint
FAIL
FAIL	github.com/cockroachdb/pebble/internal/lint	5.769s
```

The proper way to write this test would be to have it require a specific version of the linter, and do its own thing to run it, such as `go run golang.org/x/lint@some-commit args...`.

Alternatively, the bare minimum would be to skip the test if `golint` is not installed. That would still mean people could have different versions, though.

Also, beware that golint has been deprecated for some time: https://github.com/golang/go/issues/38968

### PR DESCRIPTION
**Pull request by nicktrav**
Versions of Go >= 1.17 support using the `go run path@version` syntax to
run a binary at a given version. Making use of this syntax removes the
need to install the lint binaries ahead of time (i.e. developer or CI
runs `go get ...` to install the tool).

Remove the need to install the tools in preparation for a CI run.

Bump the `staticcheck` version to `2022.1.2`, which supports Go 1.18.

Fix #1319.

### CODE REVIEW

File: internal/lint/lint_test.go [hunk 1]
```diff
@@ -59,13 +67,23 @@ func TestLint(t *testing.T) {
 	}
 
 	t.Run("TestGolint", func(t *testing.T) {
+		// Go versions less than 1.17 do not support the `go run path@version`
```
Comment (nicktrav) [inline internal/lint/lint_test.go:70]: Alternatively - we could just drop CI support for go1.16, which would avoid the need for this version parsing.

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1806#-:-N7750YIDocCI6nkgCim:bnfp4nl)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @jbowens)

**Comment by nicktrav** [comment]
TFTR!
