### PR TITLE
sstable: use columnar properties block only in v7+

### LINKED ISSUE #4727: readMetaIndex: index out of range
This was uncovered when trying to add `testserver`-based 25.2 configs to logictests in https://github.com/cockroachdb/cockroach/pull/146641

I think this is because we switched the metaindex to columnar but we expect it to be columnar even for older formats?

After initializing a node with 25.2.0-rc.1 and stopping it, when we start with master, we see:

```
panic: column 0 is type %!s(PANIC=String method: runtime error: index out of range [84] with length 5); not bytes
        panic: Release called on a BufferPool with in-use buffers

goroutine 140 [running]:
github.com/cockroachdb/pebble/sstable/block.(*BufferPool).Release(0x140019022a0)
        external/com_github_cockroachdb_pebble/sstable/block/buffer_pool.go:177 +0xfc
panic({0x1096aad00?, 0x14002aa6560?})
        GOROOT/src/runtime/panic.go:791 +0x124
github.com/cockroachdb/pebble/sstable/colblk.DecodeColumn[...](0x140000bfa60?, 0x96fa, 0x274?, 0x3?, 0x0)
        external/com_github_cockroachdb_pebble/sstable/colblk/block.go:292 +0x2ac
github.com/cockroachdb/pebble/sstable/colblk.(*BlockDecoder).RawBytes(...)
        external/com_github_cockroachdb_pebble/sstable/colblk/block.go:353
github.com/cockroachdb/pebble/sstable/colblk.(*KeyValueBlockDecoder).Init(0x14002ecba10, {0x136dfc150?, 0x10e41b180?, 0x0?})
        external/com_github_cockroachdb_pebble/sstable/colblk/key_value_block.go:84 +0x108
github.com/cockroachdb/pebble/sstable.(*Reader).readMetaindex(0x140043a4c88, {0x109e37148, 0x10e41b180}, {0x109e3cfd8, 0x14001163ae0}, 0x14001e9a360, 0x14001151bc0)
        external/com_github_cockroachdb_pebble/sstable/reader.go:492 +0x33c
github.com/cockroachdb/pebble/sstable.NewReader({0x109e37148, 0x10e41b180}, {0x109e3cfa0, 0x14002023e80}, {{{0x1400195a980, 0x1d}, 0x14001162640, {0x109e60ae0, 0x14002405530}}, 0x14001151bc0, ...})
        external/com_github_cockroachdb_pebble/sstable/reader.go:896 +0x2ec
github.com/cockroachdb/pebble.(*fileCacheHandle).openFile(0x14001ba5a40, {0x109e37148, 0x10e41b180}, 0x1d, 0x2)
        external/com_github_cockroachdb_pebble/file_cache.go:214 +0x2a4
github.com/cockroachdb/pebble.NewFileCache.func1({0x109e37148, 0x10e41b180}, {0x14001ba5a40?, 0x14001ba5a40?, 0x0?}, {0x1400201f760?, 0x14001dc8300?})
        external/com_github_cockroachdb_pebble/file_cache.go:441 +0x144
github.com/cockroachdb/pebble/internal/genericcache.(*shard[...]).findOrCreateValue(0x109f182a0, {0x109e37148, 0x10e41b180}, {0x14001ba5a40, 0x1d, 0x2})
        external/com_github_cockroachdb_pebble/internal/genericcache/shard.go:191 +0x4d0
github.com/cockroachdb/pebble/internal/genericcache.(*Cache[...]).FindOrCreate(0x109edf040, {0x109e37148, 0x10e41b180}, {0x14001ba5a40, 0x140018ccec0?, 0x0?})
        external/com_github_cockroachdb_pebble/internal/genericcache/cache.go:84 +0x98
github.com/cockroachdb/pebble.(*fileCacheHandle).findOrCreateTable(0x14001ba5a40, {0x109e37148?, 0x10e41b180?}, 0x14000a59540)
        external/com_github_cockroachdb_pebble/file_cache.go:243 +0x64
github.com/cockroachdb/pebble.(*fileCacheHandle).withReader(0x14001ba5a40, {0x109e37148?, 0x10e41b180?}, {0x0, 0x0, 0x0, 0x0, {0x0, 0x0}}, 0x14000a59540, ...)
        external/com_github_cockroachdb_pebble/file_cache.go:335 +0x5c
github.com/cockroachdb/pebble.(*DB).estimateSizesBeneath-range1(0x140000c06e0?)
        external/com_github_cockroachdb_pebble/table_stats.go:531 +0x138
github.com/cockroachdb/pebble.(*DB).estimateSizesBeneath.LevelSlice.All.func3(0x14002ecc980)
        external/com_github_cockroachdb_pebble/internal/manifest/level_metadata.go:282 +0x78
github.com/cockroachdb/pebble.(*DB).estimateSizesBeneath(0x14004486908, 0x140011eb008, 0x14001ba5a40?, 0x14002910c80, 0x140000c0af8?)
        external/com_github_cockroachdb_pebble/table_stats.go:526 +0x264
github.com/cockroachdb/pebble.(*DB).loadTablePointKeyStats(0x0?, 0x14002eccbc0, 0x14001dc8280?, 0x1400201f480?, 0x14002910c80, 0x14002eccdf8)
        external/com_github_cockroachdb_pebble/table_stats.go:361 +0x3c
github.com/cockroachdb/pebble.(*DB).loadTableStats.func1(0x140043a4a08, {0x0, 0x0, {0x0, 0x0, 0x0, 0x140018cd030, {0x109c93d80, 0x14002910c80}}})
        external/com_github_cockroachdb_pebble/table_stats.go:327 +0x298
github.com/cockroachdb/pebble.(*fileCacheHandle).withReader(0x14001ba5a40, {0x109e37148?, 0x10e41b180?}, {0x0, 0x0, 0x0, 0x140018cd030, {0x109c93d80, 0x14002910c80}}, 0x14002910c80, ...)
        external/com_github_cockroachdb_pebble/file_cache.go:356 +0x184
github.com/cockroachdb/pebble.(*DB).loadTableStats(0x0?, 0x0?, 0x14004140eb8?, 0x1027a762c?)
        external/com_github_cockroachdb_pebble/table_stats.go:311 +0xc8
github.com/cockroachdb/pebble.(*DB).loadNewFileStats(0x14004486908, 0x14000065d40, {0x14001163950, 0x3, 0x0?})
        external/com_github_cockroachdb_pebble/table_stats.go:198 +0x108
github.com/cockroachdb/pebble.(*DB).collectTableStats(0x14004486908)
        external/com_github_cockroachdb_pebble/table_stats.go:113 +0x1f0
created by github.com/cockroachdb/pebble.(*DB).maybeCollectTableStatsLocked in goroutine 131
        external/com_github_cockroachdb_pebble/table_stats.go:54 +0xd4
```

Jira issue: PEBBLE-445

### PR DESCRIPTION
**Pull request by RaduBerinde**
The change to use columnar encoding for the properties block did not
make it into the 25.2 branch, which produces v6 tables with row
encoding for the properties block.

We move this feature to v7+, which should unblock 25.2-to-master
upgrades.

Fixes #4727

### CODE REVIEW

File: sstable/reader.go [hunk 1]
```diff
@@ -534,6 +523,29 @@ func (r *Reader) readMetaindex(
 	return nil
 }
 
+// readProperties decodes the (uncompressed) properties block.
```
Comment (annrpom) [inline sstable/reader.go:526]: nit: `readPropertiesBlock`

**Review by annrpom — APPROVED** [review]
:lgtm: thank you for putting this up!!

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

I verified that `dev testlogic --files mixed_version_bootstrap_tenant --config cockroach-go-testserver-25.2` passes with this change and https://github.com/cockroachdb/cockroach/pull/146641

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4730#-:-OQJydzz9coDcC8O9hE9:butcqac)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @jbowens)

**Comment by RaduBerinde** [comment]
It would be good if someone double-checked my finding that both the current `release-25.2` head and `v25.2.0-rc.1` always encodes a columnar metaindex and a row properties block for v6.

```
cockroach # git show origin/release-25.2:go.mod | ag pebble
        github.com/cockroachdb/pebble v0.0.0-20250514173446-7873fded2160
cockroach # git show v25.2.0-rc.1:go.mod | ag pebble
        github.com/cockroachdb/pebble v0.0.0-20250421220617-b3593b89b272


pebble # git log -1000 7873fded2160 --oneline | ag columnar
c7d64e91 db: enable columnar blocks by default
bf0ffe45 db: respect EnableColumnarBlocks option on recent FMVs
72cf350a colblk: use new key value columnar block for metaindex
d78b36ea sstable: guard against double Close in columnar sstable writer
b3993ff6 db: persist Experimental.EnableColumnarBlocks in OPTIONS file
...

pebble # git log -1000 b3593b89b272 --oneline | ag columnar
c7d64e91 db: enable columnar blocks by default
bf0ffe45 db: respect EnableColumnarBlocks option on recent FMVs
72cf350a colblk: use new key value columnar block for metaindex
d78b36ea sstable: guard against double Close in columnar sstable writer
b3993ff6 db: persist Experimental.EnableColumnarBlocks in OPTIONS file
...

pebble # git log -1000 origin/master --oneline | ag columnar
bf1dcd08 db: enable columnar blocks by default
8e863788 db: respect EnableColumnarBlocks option on recent FMVs
5242eb16 colblk: use key value columnar block for properties                         <-----
72cf350a colblk: use new key value columnar block for metaindex
d78b36ea sstable: guard against double Close in columnar sstable writer
b3993ff6 db: persist Experimental.EnableColumnarBlocks in OPTIONS file
...

```

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 3 of 20 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4730#-:-OQKHLBBBUtPacbhbVuA:bnfp4nl)* status: 5 of 20 files reviewed, 1 unresolved discussion (waiting on @annrpom)

___
*[`sstable/layout.go` line 590 at r2](https://reviewable.io/reviews/cockroachdb/pebble/4730#-OQKHCHAD4095dbPHtFt:-OQKHCHAD4095dbPHtFu:b-jufi1r) ([raw file](https://github.com/cockroachdb/pebble/blob/667e2ca7dccf0f360d2b3ac5d97d808f3fb642f3/sstable/layout.go#L590)):*
> ```Go
> 		return Layout{}, errors.Wrap(err, "decompressing properties")
> 	}
> 	props, err := decodePropertiesBlock(tableFormat, decompressedProps, nil /* deniedUserPropertie */)
> ```

nit: `deniedUserProperties`

**Comment by RaduBerinde** [comment]
Thank you!
