### PR TITLE
reduce TestFlushDelayStress runs in slow builds

### LINKED ISSUE #4843: master: nightly linux-qemu-s390x test failed
The nightly linux-qemu-s390x test run failed on 38d40226616ca4699293d09afd98b82737863b1d. Please review the run [here](https://github.com/cockroachdb/pebble/actions/runs/15506765013).

Jira issue: PEBBLE-474

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #4843

### CODE REVIEW

File: db.go [hunk 1]
```diff
@@ -2979,7 +2979,7 @@ type ScanStatisticsOptions struct {
 
 // ScanStatistics returns the count of different key kinds within the lsm for a
 // key span [lower, upper) as well as the number of snapshot keys.
-func (d *DB) ScanStatistics(
+func (d *DB) ScanStatitics(
```
Comment (annrpom) [inline db.go:2982]: i think this was accidental

**Review by annrpom — APPROVED** [review]
:lgtm:

File: db.go (hunk 1 above)
Comment (RaduBerinde) [reply db.go]: :joy: Fixed!

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/4880#-:-OSQOJ-G3ldX8-ZsunHz:b-814g8k)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @annrpom and @sumeerbhola)
